# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: SiakHooi.FiboPlanner
PackageVersion: 0.7.1
PackageLocale: en-US
Publisher: Siak Hooi
PublisherUrl: https://github.com/siakhooi
PublisherSupportUrl: https://github.com/siakhooi/fibo-planner/issues
PackageName: FiboPlanner
PackageUrl: https://github.com/siakhooi/fibo-planner
License: MIT
LicenseUrl: https://github.com/siakhooi/fibo-planner/blob/main/LICENSE
Copyright: Copyright (c) Siak Hooi
ShortDescription: CLI client for FiboPlanner
Description: web app to run planning poker technique
Moniker: fibo-planner
Tags:
- FiboPlanner
- PlanningPoker
ReleaseNotesUrl: https://github.com/siakhooi/fibo-planner/releases/tag/v0.7.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
