# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: SiakHooi.FiboPlanner
PackageVersion: 0.7.1
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: fibo-planner.exe
  PortableCommandAlias: fibo-planner
UpgradeBehavior: install
Commands:
- fibo-planner
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/siakhooi/fibo-planner/releases/download/v0.7.1/fibo-planner_0.7.1_Windows_x86_64.zip
  InstallerSha256: 7e70819002bb146e5e3bb44f0a047c8d95440867bcda9f71a0c247264dd6a347
- Architecture: arm64
  InstallerUrl: https://github.com/siakhooi/fibo-planner/releases/download/v0.7.1/fibo-planner_0.7.1_Windows_arm64.zip
  InstallerSha256: 774df7adc6f7b1fb9442bd271c8cb3fc5efb16f8e922f2f5e824b7dc9cfef3b8
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-09-28
